"""Regenerate ENVIRONMENT.md from the current interpreter/OS/BLAS state.

Run via `make install` (or directly: `python scripts/record_environment.py`)
so ENVIRONMENT.md always reflects the environment that actually produced
the results in this repo, rather than being hand-maintained.
"""

from __future__ import annotations

import io
import platform
import subprocess
import sys
from contextlib import redirect_stdout
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def get_cpu_model() -> str:
    system = platform.system()
    try:
        if system == "Windows":
            # `wmic` is deprecated/absent on newer Windows builds, so read the
            # registry value directly rather than shelling out to it.
            import winreg

            key = winreg.OpenKey(
                winreg.HKEY_LOCAL_MACHINE,
                r"HARDWARE\DESCRIPTION\System\CentralProcessor\0",
            )
            name, _ = winreg.QueryValueEx(key, "ProcessorNameString")
            return name.strip()
        elif system == "Linux":
            text = Path("/proc/cpuinfo").read_text()
            for line in text.splitlines():
                if line.lower().startswith("model name"):
                    return line.split(":", 1)[1].strip()
        elif system == "Darwin":
            out = subprocess.run(
                ["sysctl", "-n", "machdep.cpu.brand_string"],
                capture_output=True,
                text=True,
                timeout=10,
                check=True,
            ).stdout
            return out.strip()
    except Exception as exc:  # best effort -- environment recording must not hard-fail
        return f"<could not determine CPU model: {exc}>"
    return platform.processor() or "<unknown>"


def get_numpy_config() -> str:
    import numpy as np

    buf = io.StringIO()
    with redirect_stdout(buf):
        np.show_config()
    return buf.getvalue().strip()


def get_installed_versions() -> list[str]:
    out = subprocess.run(
        [sys.executable, "-m", "pip", "freeze"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return sorted(out.splitlines(), key=str.lower)


def main() -> None:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")
    cpu_model = get_cpu_model()
    numpy_config = get_numpy_config()
    versions = get_installed_versions()

    content = f"""# Environment

Auto-generated by `scripts/record_environment.py` -- do not hand-edit.
Regenerate with `make install` (or `python scripts/record_environment.py`)
whenever the environment changes, so this file stays truthful.

Last recorded: {now}

## Python

- Version: {platform.python_version()}
- Implementation: {platform.python_implementation()}
- Executable: {sys.executable}

## Operating System

- System: {platform.system()} {platform.release()}
- Version: {platform.version()}
- Machine: {platform.machine()}
- Platform string: {platform.platform()}

## CPU

- Model: {cpu_model}
- Logical CPU count: {__import__("os").cpu_count()}

## NumPy BLAS/LAPACK backend (`numpy.show_config()`)

```
{numpy_config}
```

## Installed package versions (`pip freeze`)

```
{chr(10).join(versions)}
```
"""

    out_path = REPO_ROOT / "ENVIRONMENT.md"
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
